### ISSUE TITLE
<script lang="ts">，不引用src，直接在script里编写TS代码时，props无法被渲染

### ISSUE THREAD

**Issue by youngcube** [WingGao/mpvue-ts-demo#10]
`./src/components/card.vue ` 中有一段代码是

```
<script>
export default {
  props: ["text"]
};
</script>
```

如果第一句改成 `<script lang="ts">` 那么父组件传给 Card 组件的 text 就不会被渲染了

**Comment by WingGao** [comment]
对的，`<script lang="ts">`这种写法只支持外部ts文件，这个`card.vue`是原生的vue单文件写法。

**Comment by youngcube** [comment]
好吧 
这样是无解的吗？ 如果没办法就请关闭吧。
本以为是可以直接在 Vue 里面的 <script> 标签直接写 ts 的，这样看来还得再加个文件出来
谢谢

**Comment by linfan68** [comment]
@youngcube 不是这个意思。是可以在.vue里面写ts的，但是如果要用ts定义组件需要用class-sytle定义component：
https://github.com/vuejs/vue-class-component
和代码写在.vue里面还是外面没关系，你可以试着把CompB外面的ts文件内容拷到.vue里面的<script>里面试试看

**Comment by linfan68** [comment]
@youngcube 但是我们用mpvue+ts做了个挺大的项目，我还是建议吧ts文件分开。我们用VsCode做开发，如果ts代码写在vue里面的话代码重构（比如重命名）不会改.vue里面的ts code。而且语法高亮和提示貌似也是在ts文件里面靠谱一些

**Comment by WingGao** [comment]
确实如 @linfan68  所说。团队使用的时候，独立文件配合lint等其他工具是非常方便的，而单文件目前没有这方面的支持。

**Comment by youngcube** [comment]
非常感谢二位的回答
我也老老实实单独使用 ts 文件吧
