### ISSUE TITLE
counter.ts 里面 怎么不能使用typescript 类型定义

### ISSUE THREAD

**Issue by angrycans** [WingGao/mpvue-ts-demo#2]
counter.ts  比如在 第7行 加上
let s:string 

就不能编译了

**Comment by angrycans** [comment]
或者在下面的class 里面也不能写typescript 语法

**Comment by WingGao** [comment]
目前正在解决，是mpvue-loader的问题

**Comment by WingGao** [comment]
已解决，等待mpvue-loader的合并处理
https://github.com/mpvue/mpvue-loader/pull/8

**Comment by WingGao** [comment]
如果想直接使用可以使用https://github.com/WingGao/mpvue-ts-demo/tree/dev分支
然后重新`yarn`或者`npm install`
