### ISSUE TITLE
Number.parseInt使用导致项目编译报错

### ISSUE THREAD

**Issue by UniqueCrownClown** [WingGao/mpvue-ts-demo#23]
Number.parseInt使用导致项目编译报错，up主这是为啥呢

**Comment by WingGao** [comment]
是不是添加lint?

**Comment by UniqueCrownClown** [comment]
是eslintrc.js还是eslint-loader的地方么，webpack用的就是这个demo的，没看到有啥配置，不确定是不是有问题，我改成了用Number构造

**Comment by WingGao** [comment]
对，旧的`build/webpack.base.conf.js`里有个 `eslint-loader`不需要可以直接注释掉，没什么影响
