### ISSUE TITLE
出现脚本错误或者未正确调用 Page()

### ISSUE THREAD

**Issue by Leeero** [WingGao/mpvue-ts-demo#26]
你好，请问一下，为什么我通过<script lang="ts" src="./XXXXX.ts"></script> 这种方式引入 ts 文件之后会导致整个小程序编译完成之后无法运行呢，在控制台会有错误提示：出现脚本错误或者未正确调用 Page()。

**Comment by mrlizonglin** [comment]
@WingGao 大佬，救命

**Comment by linfan68** [comment]
是直接用这个项目编译的么？还是自己的项目？
如果是自己的项目看一下生成的文件（.js，wxml这些）有没有问题，和这个项目比较一下，一般是mpvue几个东西的版本问题

**Comment by linfan68** [comment]
> @WingGao 大佬，救命

和这位兄弟多说两句，求助问问题不是这么问的。你的环境是怎么样的，各个包的版本。代码是这里原始的代码还是改过的。更重要的是你尝试过哪些debug的方法，google搜过没有？小程序社区搜过没有？生成的代码观察到哪些不对劲的地方？这些功课做了以后大家才能帮你不是。

**Comment by WingGao** [comment]
不好意思啊各位，最近有点忙，等会儿我看下哈
________________________________

**Comment by WingGao** [comment]
@mrlizonglin 我试了下并没有发现，你能提供一下demo嘛？

**Comment by mrlizonglin** [comment]
@WingGao 你好，感谢回复，目前复现的场景是我参考这个项目改造我自己的项目而出现的。控制台出现错误的原因是因为编译后xml文件里的引用不对导致的，具体如下：
失败：
<import src="/pages/forward/forward.ts.wxml" /><template is="0d15cb70" data="{{ ...$root['0'], $root }}"/>
正确的应该是：
<import src="/pages/forward/forward.vue.wxml" /><template is="0d15cb70" data="{{ ...$root['0'], $root }}"/>
猜测应该是编译时参数设置错误或者说漏了哪个步骤导致的。
如果描述的还不够清楚，那我再补充，多谢。
另附上主要包的版本：
 "mpvue-entry": "1.5.9",
    "mpvue-loader": "1.4.0",
    "mpvue-template-compiler": "1.4.4",
    "mpvue-webpack-target": "^1.0.0",
"webpack": "^3.11.0",

**Comment by mrlizonglin** [comment]
@linfan68 ，谢谢指导如何提问，后面的几个提问，我都已经做过了，只不过没在提问中说到确实是我的问题。

**Comment by Leeero** [comment]
@WingGao ，您好，感谢回复。请问我能通过邮件跟您沟通吗？具体的demo我在邮件里附上。
