### ISSUE TITLE
不能使用components

### ISSUE THREAD

**Issue by zhangchen91** [WingGao/mpvue-ts-demo#3]
代码如下：
![image](https://user-images.githubusercontent.com/1012304/37821309-344a6da6-2ebe-11e8-8fb1-f61ed3c46fa2.png)

结果如下：
![image](https://user-images.githubusercontent.com/1012304/37821410-75169c9c-2ebe-11e8-81b9-910e5492b34b.png)

组件对应的生命周期都触发了，但是在Wxml节点里不渲染

**Comment by WingGao** [comment]
目前正在解决，是mpvue-loader的问题

**Comment by WingGao** [comment]
已解决，等待mpvue-loader的合并处理
https://github.com/mpvue/mpvue-loader/pull/8

**Comment by WingGao** [comment]
如果想直接使用可以使用https://github.com/WingGao/mpvue-ts-demo/tree/dev分支
然后重新`yarn`或者`npm install`
