### ISSUE TITLE
因为Vue的Type定义问题，不能使用小程序自己的生命周期

### ISSUE THREAD

**Issue by zhangchen91** [WingGao/mpvue-ts-demo#4]
![image](https://user-images.githubusercontent.com/1012304/38035578-4bddc8b0-32d7-11e8-8a14-a12011cab22e.png)

**Comment by WingGao** [comment]
fixed https://github.com/WingGao/mpvue-ts-demo/commit/bee260b1a4220377e45246e7944715fa21f478fb
