### ISSUE TITLE
App 必须设置 mpType 为 'app'

### ISSUE THREAD

**Issue by fengcen** [WingGao/mpvue-ts-demo#5]
否则无法获取场景值，也不能触发 onLaunch 等 app 相关的生命周期函数。

**Comment by fengcen** [comment]
并且 App.vue 不能使用 `lang="ts"`，否则 `appOptions` 的值也是空的，不清楚原因。

**Comment by WingGao** [comment]
fixed https://github.com/WingGao/mpvue-ts-demo/commit/15db44c9b67a689e72925fc6f079d49bb11b91dd
