### ISSUE TITLE
mpType注入问题

### ISSUE THREAD

**Issue by linfan68** [WingGao/mpvue-ts-demo#7]
基于这个项目把之前的mpvue项目整体移植到typescript，基本过程很顺利，唯一有一个地方：

## mpType怎么注入？

我看到这个demo里面两个地方做了处理：
在最外面的main.ts
https://github.com/WingGao/mpvue-ts-demo/blob/dev/src/main.ts
```ts
interface IMpVue extends VueConstructor {
  mpType: string
}

// ...Other code...

// 在这个地方引入是为了registerHooks先执行
const MyApp = require('./App.vue').default as IMpVue
```

和app.ts
https://github.com/WingGao/mpvue-ts-demo/blob/dev/src/app.ts
```ts
// 必须使用装饰器的方式来指定components
@Component({
  mpType: 'app', // mpvue特定
}as any)
class App extends Vue {
```

我理解main.ts应该是之前的尝试失败了忘了删掉?
有用的是app.ts里面的这个，如果没有的话app的微信事件onLaunch啥的都没有

但是我发现这样的副作用是这样的：
如果在Page里面做同样的事情：
```ts
@Component({
  components: { HelloWorld },
  mpType: 'page'
} as any)
export default class Page extends Vue {
```
结局是自定义组件（`HelloWorld`）没有注册上！页面上渲染不出来

问题出在 `as any` 上， 比如这样也是不行的：
```ts
@Component({
  components: { HelloWorld }
} as any)
export default class Page extends Vue {
```
但是如果没有`as any`的话（可能你也试过）ts编译不过……

目前问题貌似不是很大，因为看了mpvue的代码如果没有定义mpType的话默认是`‘page’`
但是正确的解法是什么呢？比如还有一个mpType是`‘component’` 到时候就麻烦了……

（写了一个多星期的JS完全崩溃了，没有compiler写出来全是runtime error，前端的大佬们都是什么样的存在……）

**Comment by linfan68** [comment]
应该不是这个问题，整个Page的code就是这样：
```vue
<template>
  <hello-world></hello-world>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import HelloWorld from '@/components/HelloWorld.vue'

@Component({ components: { HelloWorld } } as any)
export default class Page extends Vue {

}
</script>

<style scoped>
</style>
```

注意`@Component(...)` 里面的`as any`：
没有`as any`的时候在dist里面生成的wxml：
```xml
<import src="HelloWorld$d21a6632" />
<template name="index$f6f5c1de">
  <template data="{{...$root[$kk+'0'], $root}}" is="HelloWorld$d21a6632"></template>
</template>
```

加上之后：
```xml
<template name="index$f6f5c1de">
  <hello-world class="_hello-world data-v-d57e162e"></hello-world>
</template>
```
所以渲染不出来也是正常的，没有正确的转成小程序的wxml

因为wxml是mpvue-loader编译时生成的，我debug了一下mpvue-loader，确实是加了any之后component list没有识别出来。目前找到问题可能在这个地方
mpvue-loader\lib\mp-compiler\parse-ts.js

```js
function parseDecorator (node) {
    // 只处理 @Component({components:{aaa}})
    if (node.expression.expression && node.expression.expression.escapedText === 'Component') {
      const compArgs = node.expression.arguments
      if (compArgs && compArgs.length === 1) {
        const vueClassArg = compArgs[0]
        if (vueClassArg.properties) {
          vueClassArg.properties.forEach((classProp) => {
            // 处理components属性
            if (classProp.name.escapedText === 'components') {
              classProp.initializer.properties.forEach((comp) => {
   ...
```
目测整体的思路是mpvue-loader吧ts文件内容动态的扔给ts compiler，然后从里面找到`@Component({components:{aaa}})` 这样的字段，然后来生成这个page使用的component表。介于小程序所有的DOM都要是静态的，这也是没有办法的办法了……

所以我判断加了as any的问题应该就是break了这个地方的假设

如果这样的话，我目前的思路是自己写一个class decorator来注入mpType，比如这样是可以的：
```
@Component({ components: { HelloWorld } }) // 让mpvue-loader高兴
@Component({ components: { HelloWorld }, mpType: 'page' } as any)
export default class Page extends Vue {

}
```

甚至这样也是可以的：
```
@Component({ components: { HelloWorld }, mpType: 'page' } as any)
export default class Page extends Vue {
}

@Component({ components: { HelloWorld } }) // make mpvue-loader happy
class Page2 extends Vue {}
```
但就是这个@Component里面还挺复杂的……还没琢磨出来怎么写

**Comment by WingGao** [comment]
我把尝试的代码推了上来，按理说来ts应该是可以解析的，你可以试一下这个分支https://github.com/WingGao/mpvue-ts-demo/compare/issue7
顺便可以的花，你能把`HelloWorld `的代码贴一下吗？

**Comment by WingGao** [comment]
刚刚又尝试了下，你的结论是对的，当时候忘记处理`as`的情况，目前已加上。谢谢！
https://github.com/mpvue/mpvue-loader/pull/22

**Comment by linfan68** [comment]
给力！非常感谢！
